# Metadata for all Bacon test suites. For options, see:
# https://oktawiki.atlassian.net/wiki/spaces/ESS/pages/635280223/Flexible+Test+Suites
test_suites:
  # Required test suites
  - name: unit-test-ios
    script_path: okta-logger-swift/ci-build
    sort_order: '2'
    timeout: '10'
    script_name: test
    criteria: MERGE
    queue_name: dart-ios-verify-ci-build

 - name: lint
    script_path: okta-logger-swift/ci-build
    sort_order: '2'
    timeout: '10'
    script_name: lint
    criteria: MERGE
    queue_name: dart-ios-verify-ci-build
    script_env:
	DEVICE_NAME: "iPhone 11"

